/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentinformationsystem;

import java.awt.*;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.*;

public class AdminIndividualStaff extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form Staff_details
     */
    public AdminIndividualStaff() {
        initComponents();
        conn = dbconnect.java_db();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2,
                size.height / 2 - getHeight() / 2);
        setResizable(false);
        setTitle("Seethawakapura Urban Council, Avissawella");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldSearchPersonByIDStaff = new javax.swing.JTextField();
        jButtonLogOutStaff = new javax.swing.JButton();
        jButtonUpdateStaff = new javax.swing.JButton();
        jButtonDeleteStaff = new javax.swing.JButton();
        jButtonResetStaff = new javax.swing.JButton();
        jButtonBackStaff = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelFormNoStaff = new javax.swing.JLabel();
        jLabelFNameStaff = new javax.swing.JLabel();
        jTextFieldFormNoStaff = new javax.swing.JTextField();
        jTextFieldFNameStaff = new javax.swing.JTextField();
        jLabelDesignationStaff = new javax.swing.JLabel();
        jTextFieldDesignationStaff = new javax.swing.JTextField();
        jLabelIDStaff = new javax.swing.JLabel();
        jTextFieldIDStaff = new javax.swing.JTextField();
        jButtonImage = new javax.swing.JButton();
        jTextFieldMNameStaff = new javax.swing.JTextField();
        jLabelMNameStaff = new javax.swing.JLabel();
        jLabelLNameStaff = new javax.swing.JLabel();
        jTextFieldLNameStaff = new javax.swing.JTextField();
        jLabelGenderStaff = new javax.swing.JLabel();
        jTextFieldGenderStaff = new javax.swing.JTextField();
        jLabelContactNoStaff = new javax.swing.JLabel();
        jTextFieldContactNoStaff = new javax.swing.JTextField();
        jLabelBDayStaff = new javax.swing.JLabel();
        jTextFieldBdayStaff = new javax.swing.JTextField();
        jLabelGradeStaff = new javax.swing.JLabel();
        jTextFieldGradeStaff = new javax.swing.JTextField();
        jLabelAppointmentDateStaff = new javax.swing.JLabel();
        jTextFieldAppointmentDateStaff = new javax.swing.JTextField();
        jLabelCivilStatusStaff = new javax.swing.JLabel();
        jTextFieldCivilStatusStaff = new javax.swing.JTextField();
        jLabelAddressStaff = new javax.swing.JLabel();
        jTextFieldAddressStaff = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lbl_img = new javax.swing.JLabel();
        lbl_img1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setBackground(new java.awt.Color(0, 51, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentinformationsystem/header_1.jpg"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Search Person By ID");

        jTextFieldSearchPersonByIDStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchPersonByIDStaffActionPerformed(evt);
            }
        });
        jTextFieldSearchPersonByIDStaff.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSearchPersonByIDStaffKeyReleased(evt);
            }
        });

        jButtonLogOutStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentinformationsystem/logout.png"))); // NOI18N
        jButtonLogOutStaff.setText("Logged Out");
        jButtonLogOutStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogOutStaffActionPerformed(evt);
            }
        });

        jButtonUpdateStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentinformationsystem/update icon.png"))); // NOI18N
        jButtonUpdateStaff.setText("Update");
        jButtonUpdateStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateStaffActionPerformed(evt);
            }
        });

        jButtonDeleteStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentinformationsystem/delete_16x16.gif"))); // NOI18N
        jButtonDeleteStaff.setText("Delete");
        jButtonDeleteStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteStaffActionPerformed(evt);
            }
        });

        jButtonResetStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentinformationsystem/erase-128.png"))); // NOI18N
        jButtonResetStaff.setText("Reset");
        jButtonResetStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetStaffActionPerformed(evt);
            }
        });

        jButtonBackStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentinformationsystem/back.png"))); // NOI18N
        jButtonBackStaff.setText("Back");
        jButtonBackStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackStaffActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabelFormNoStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelFormNoStaff.setText("W&OP Number");

        jLabelFNameStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelFNameStaff.setText("First Name");

        jTextFieldFormNoStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldFormNoStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFormNoStaffActionPerformed(evt);
            }
        });

        jTextFieldFNameStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabelDesignationStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelDesignationStaff.setText("Designation");

        jTextFieldDesignationStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabelIDStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelIDStaff.setText("Identity Number");

        jTextFieldIDStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldIDStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDStaffActionPerformed(evt);
            }
        });

        jButtonImage.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonImage.setText(" Images");
        jButtonImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImageActionPerformed(evt);
            }
        });

        jTextFieldMNameStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabelMNameStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelMNameStaff.setText("Middle Name");

        jLabelLNameStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelLNameStaff.setText("Last Name");

        jTextFieldLNameStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabelGenderStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelGenderStaff.setText("Gender");

        jTextFieldGenderStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabelContactNoStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelContactNoStaff.setText("Contact Number");

        jTextFieldContactNoStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabelBDayStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelBDayStaff.setText("Date of Birth");

        jTextFieldBdayStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldBdayStaff.setText("year/month/days");

        jLabelGradeStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelGradeStaff.setText("Grade");

        jTextFieldGradeStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabelAppointmentDateStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelAppointmentDateStaff.setText("First Appointment Date");

        jTextFieldAppointmentDateStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabelCivilStatusStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCivilStatusStaff.setText("Civil Status");

        jTextFieldCivilStatusStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabelAddressStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelAddressStaff.setText(" Address");

        jTextFieldAddressStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 153));
        jLabel6.setText("Personal Details");

        lbl_img1.setBackground(new java.awt.Color(0, 0, 153));
        lbl_img1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_img1.setForeground(new java.awt.Color(0, 51, 153));
        lbl_img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentinformationsystem/Person.png"))); // NOI18N
        lbl_img1.setText("      Image Attach Here");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelGradeStaff)
                                    .addComponent(jLabelCivilStatusStaff)
                                    .addComponent(jLabelContactNoStaff))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldCivilStatusStaff, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                    .addComponent(jTextFieldGradeStaff, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldContactNoStaff)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelFormNoStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldFormNoStaff))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelGenderStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jTextFieldGenderStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelFNameStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldFNameStaff)))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabelAppointmentDateStaff)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldAppointmentDateStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jLabelMNameStaff)
                                                    .addGap(30, 30, 30))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jLabelIDStaff)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabelBDayStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(26, 26, 26)))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldIDStaff, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                            .addComponent(jTextFieldMNameStaff, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                            .addComponent(jTextFieldBdayStaff))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabelDesignationStaff)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldDesignationStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabelLNameStaff)
                                        .addGap(29, 29, 29)
                                        .addComponent(jTextFieldLNameStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelAddressStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(85, 85, 85)
                                .addComponent(jTextFieldAddressStaff)
                                .addGap(32, 32, 32)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButtonImage, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lbl_img1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(487, 487, 487)
                    .addComponent(lbl_img, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addGap(488, 488, 488)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lbl_img1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButtonImage, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFormNoStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFormNoStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIDStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIDStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFNameStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFNameStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMNameStaff)
                    .addComponent(jTextFieldMNameStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLNameStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLNameStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGenderStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldGenderStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBDayStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBdayStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDesignationStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldDesignationStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldGradeStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGradeStaff)
                    .addComponent(jLabelAppointmentDateStaff)
                    .addComponent(jTextFieldAppointmentDateStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCivilStatusStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCivilStatusStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAddressStaff)
                    .addComponent(jTextFieldAddressStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldContactNoStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelContactNoStaff))
                .addGap(202, 202, 202))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(200, 200, 200)
                    .addComponent(lbl_img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(200, 200, 200)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldSearchPersonByIDStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonResetStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDeleteStaff)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonUpdateStaff)
                        .addGap(7, 7, 7)
                        .addComponent(jButtonBackStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLogOutStaff))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldSearchPersonByIDStaff, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6))
                    .addComponent(jButtonBackStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonUpdateStaff, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDeleteStaff, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLogOutStaff, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonResetStaff, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImageActionPerformed
        // TODO add your handling code here:

        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();

        filename = f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lbl_img1.getWidth(), lbl_img1.getHeight(), Image.SCALE_DEFAULT));
        lbl_img1.setIcon(imageIcon);
        try {

            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];

            for (int readNum; (readNum = fis.read(buf)) != -1;) {

                bos.write(buf, 0, readNum);
            }
            person_image = bos.toByteArray();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButtonImageActionPerformed

    private void jTextFieldSearchPersonByIDStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchPersonByIDStaffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchPersonByIDStaffActionPerformed

    private void jTextFieldSearchPersonByIDStaffKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchPersonByIDStaffKeyReleased
        // TODO add your handling code here:
        try {
            String sql = "select * from staff where identity_number=? ";

            pst = conn.prepareStatement(sql);
            pst.setString(1, jTextFieldSearchPersonByIDStaff.getText());
            rs = pst.executeQuery();
            while (rs.next()) {

                String add1 = rs.getString("form_id");
                jTextFieldFormNoStaff.setText(add1);
                String add2 = rs.getString("designation");
                jTextFieldDesignationStaff.setText(add2);
                String add3 = rs.getString("identity_number");
                jTextFieldIDStaff.setText(add3);
                String add4 = rs.getString("first_name");
                jTextFieldFNameStaff.setText(add4);
                String add6 = rs.getString("middle_name");
                jTextFieldMNameStaff.setText(add6);
                String add7 = rs.getString("last_name");
                jTextFieldLNameStaff.setText(add7);
                String add5 = rs.getString("gender");
                jTextFieldGenderStaff.setText(add5);
                String add8 = rs.getString("contact");
                jTextFieldContactNoStaff.setText(add8);
                String add9 = rs.getString("dob");
                jTextFieldBdayStaff.setText(add9);
                String add10 = rs.getString("grade");
                jTextFieldGradeStaff.setText(add10);
                String add11 = rs.getString("first_appointment_date");
                jTextFieldAppointmentDateStaff.setText(add11);
                String add12 = rs.getString("civil_status");
                jTextFieldCivilStatusStaff.setText(add12);
                String add13 = rs.getString("address");
                jTextFieldAddressStaff.setText(add13);
                byte[] img = rs.getBytes("image");
                ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(lbl_img1.getWidth(), lbl_img1.getHeight(), Image.SCALE_SMOOTH));
                lbl_img1.setIcon(imageIcon);
            }
        } catch (Exception e) {

        } finally {

            try {

                rs.close();
                pst.close();

            } catch (Exception e) {

            }
        }


    }//GEN-LAST:event_jTextFieldSearchPersonByIDStaffKeyReleased

    private void jTextFieldFormNoStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFormNoStaffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFormNoStaffActionPerformed

    private void jButtonLogOutStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogOutStaffActionPerformed
        // TODO add your handling code here:
        new StaffDetails().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonLogOutStaffActionPerformed

    private void jButtonResetStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetStaffActionPerformed
        // TODO add your handling code here:
        jTextFieldSearchPersonByIDStaff.setText("");
        jTextFieldFormNoStaff.setText("");
        jTextFieldFNameStaff.setText("");
        jTextFieldDesignationStaff.setText("");
        jTextFieldIDStaff.setText("");
        jTextFieldMNameStaff.setText("");
        jTextFieldLNameStaff.setText("");
        jTextFieldGenderStaff.setText("");
        jTextFieldContactNoStaff.setText("");
        jTextFieldBdayStaff.setText("");
        jTextFieldGradeStaff.setText("");
        jTextFieldAppointmentDateStaff.setText("");
        jTextFieldCivilStatusStaff.setText("");
        jTextFieldAddressStaff.setText("");
        lbl_img1.setIcon(null);
    }//GEN-LAST:event_jButtonResetStaffActionPerformed

    private void jButtonDeleteStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteStaffActionPerformed
        // TODO add your handling code here:
        if (jTextFieldSearchPersonByIDStaff.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Record is Not Selected");
        } else {
            int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete record?", "Delete", JOptionPane.YES_NO_OPTION);
            if (p == 0) {
                String sql = "delete from staff where identity_number=? ";
                try {
                    pst = conn.prepareStatement(sql);
                    pst.setString(1, jTextFieldSearchPersonByIDStaff.getText());
                    pst.execute();

                    JOptionPane.showMessageDialog(null, "Record Deleted successfully");
                    jTextFieldSearchPersonByIDStaff.setText("");
                    jTextFieldFormNoStaff.setText("");
                    jTextFieldFNameStaff.setText("");
                    jTextFieldDesignationStaff.setText("");
                    jTextFieldIDStaff.setText("");
                    jTextFieldMNameStaff.setText("");
                    jTextFieldLNameStaff.setText("");
                    jTextFieldGenderStaff.setText("");
                    jTextFieldContactNoStaff.setText("");
                    jTextFieldBdayStaff.setText("");
                    jTextFieldGradeStaff.setText("");
                    jTextFieldAppointmentDateStaff.setText("");
                    jTextFieldCivilStatusStaff.setText("");
                    jTextFieldAddressStaff.setText("");
                    lbl_img1.setIcon(null);
                } catch (Exception e) {

                    JOptionPane.showMessageDialog(null, e);
                } finally {

                    try {
                        rs.close();
                        pst.close();

                    } catch (Exception e) {

                    }
                }
            }
        }
    }//GEN-LAST:event_jButtonDeleteStaffActionPerformed

    private void jButtonUpdateStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateStaffActionPerformed
        // TODO add your handling code here:
         if (jTextFieldSearchPersonByIDStaff.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Record is Not Selected");
         }else{
        int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to update?","Update Record",JOptionPane.YES_NO_OPTION);
        if(p==0){  
            try{
                String value0 = jTextFieldSearchPersonByIDStaff.getText();
                String value1 = jTextFieldFormNoStaff.getText();
                String value2 = jTextFieldFNameStaff.getText();
                String value3 = jTextFieldDesignationStaff.getText();
                String value4 = jTextFieldIDStaff.getText();
                String value5 = jTextFieldMNameStaff.getText();
                String value6 = jTextFieldLNameStaff.getText();
                String value7 = jTextFieldGenderStaff.getText();
                String value8 = jTextFieldContactNoStaff.getText();
                String value9 = jTextFieldBdayStaff.getText();
                String value10 = jTextFieldGradeStaff.getText();
                String value11 = jTextFieldAppointmentDateStaff.getText();
                String value12 = jTextFieldCivilStatusStaff.getText();
                String value13 = jTextFieldAddressStaff.getText();
               
                String sql= "update staff set form_id='"+value1+"',designation='"+value3+"', identity_number='"+value4+"', "
                        + "first_name='"+value2+"',middle_name='"+value5+"',last_name='"+value6+"',gender='"+value7+"',contact= '"+value8+"', "
                        + "dob='"+value9+"',grade ='"+value10+"',first_appointment_date='"+value11+"',civil_status='"+value12+"',address='"+value13+"'"
                       // + "image=?"
                        
                        + "where identity_number='"+value0+"' ";

                pst=conn.prepareStatement(sql);
              
                pst.execute();
                JOptionPane.showMessageDialog(null, "RecordSuccessfully Updated");

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            finally {

                try{
                    rs.close();
                    pst.close();

                }
                catch(Exception e){

                }
            }
        }
             
         }
    }//GEN-LAST:event_jButtonUpdateStaffActionPerformed

    private void jButtonBackStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackStaffActionPerformed
        // TODO add your handling code here:
        new AdminFrameStaff().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonBackStaffActionPerformed

    private void jTextFieldIDStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDStaffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDStaffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminIndividualStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminIndividualStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminIndividualStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminIndividualStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminIndividualStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBackStaff;
    private javax.swing.JButton jButtonDeleteStaff;
    private javax.swing.JButton jButtonImage;
    private javax.swing.JButton jButtonLogOutStaff;
    private javax.swing.JButton jButtonResetStaff;
    private javax.swing.JButton jButtonUpdateStaff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelAddressStaff;
    private javax.swing.JLabel jLabelAppointmentDateStaff;
    private javax.swing.JLabel jLabelBDayStaff;
    private javax.swing.JLabel jLabelCivilStatusStaff;
    private javax.swing.JLabel jLabelContactNoStaff;
    private javax.swing.JLabel jLabelDesignationStaff;
    private javax.swing.JLabel jLabelFNameStaff;
    private javax.swing.JLabel jLabelFormNoStaff;
    private javax.swing.JLabel jLabelGenderStaff;
    private javax.swing.JLabel jLabelGradeStaff;
    private javax.swing.JLabel jLabelIDStaff;
    private javax.swing.JLabel jLabelLNameStaff;
    private javax.swing.JLabel jLabelMNameStaff;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldAddressStaff;
    private javax.swing.JTextField jTextFieldAppointmentDateStaff;
    private javax.swing.JTextField jTextFieldBdayStaff;
    private javax.swing.JTextField jTextFieldCivilStatusStaff;
    private javax.swing.JTextField jTextFieldContactNoStaff;
    private javax.swing.JTextField jTextFieldDesignationStaff;
    private javax.swing.JTextField jTextFieldFNameStaff;
    private javax.swing.JTextField jTextFieldFormNoStaff;
    private javax.swing.JTextField jTextFieldGenderStaff;
    private javax.swing.JTextField jTextFieldGradeStaff;
    private javax.swing.JTextField jTextFieldIDStaff;
    private javax.swing.JTextField jTextFieldLNameStaff;
    private javax.swing.JTextField jTextFieldMNameStaff;
    private javax.swing.JTextField jTextFieldSearchPersonByIDStaff;
    private javax.swing.JLabel lbl_img;
    private javax.swing.JLabel lbl_img1;
    // End of variables declaration//GEN-END:variables
 private ImageIcon format = null;
    String filename = null;
    byte[] person_image = null;

}
