/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentinformationsystem;

import java.awt.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.*;


/**
 *
 * @author Apple
 */
public class UserIndividualStaff extends javax.swing.JFrame {

    
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form Staff_details
     */
    public UserIndividualStaff() {
        initComponents();
        conn = dbconnect.java_db();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2,
                size.height / 2 - getHeight() / 2);
        setResizable(false);
        setTitle("Steethawakapura Urban Council, Avissawella");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelSearchUserStaff = new javax.swing.JLabel();
        jTextFieldSearchUserStaff = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelFNameUserStaff = new javax.swing.JLabel();
        jTextFieldFormNoUserStaff = new javax.swing.JTextField();
        jLabelDesignationUserStaff = new javax.swing.JLabel();
        jTextFieldDesignationUserStaff = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldIDUserStaff = new javax.swing.JTextField();
        jTextFieldFNameUserStaff = new javax.swing.JTextField();
        jLabelFormNoUserStaff = new javax.swing.JLabel();
        jLabelMNameUserStaff = new javax.swing.JLabel();
        jTextFieldMNameUsrStaff = new javax.swing.JTextField();
        jLabelLNameUserStaff = new javax.swing.JLabel();
        jTextFieldLNameUserStaff = new javax.swing.JTextField();
        jLabelGenderUserStaff = new javax.swing.JLabel();
        jTextFieldGenderUserStaff = new javax.swing.JTextField();
        jLabelContactUserStaff = new javax.swing.JLabel();
        jTextFieldContactUserStaff = new javax.swing.JTextField();
        jLabelBDayUserStaff = new javax.swing.JLabel();
        jTextFieldBDayUserStaff = new javax.swing.JTextField();
        jLabelGrdeUserStaff = new javax.swing.JLabel();
        jTextFieldCivilStatusUserStaff = new javax.swing.JTextField();
        jLabelAppointmentUserStaff = new javax.swing.JLabel();
        jTextFieldAppointmentUserStaff = new javax.swing.JTextField();
        jLabelAddressUserStaff = new javax.swing.JLabel();
        jLabelCivilStatusUserStaff = new javax.swing.JLabel();
        jTextFieldAddressStaff = new javax.swing.JTextField();
        jTextFieldGradeUserStaff = new javax.swing.JTextField();
        lbl_img1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jButton4.setBackground(new java.awt.Color(0, 51, 153));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentinformationsystem/headeruser_1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton4)
        );

        jPanel2.setBackground(new java.awt.Color(0, 51, 153));

        jLabelSearchUserStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSearchUserStaff.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSearchUserStaff.setText("Search Person By ID");

        jTextFieldSearchUserStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchUserStaffActionPerformed(evt);
            }
        });
        jTextFieldSearchUserStaff.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSearchUserStaffKeyReleased(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentinformationsystem/logout.png"))); // NOI18N
        jButton1.setText("Logged Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentinformationsystem/erase-128.png"))); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentinformationsystem/next.png"))); // NOI18N
        jButton3.setText("Next");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabelSearchUserStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldSearchUserStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelSearchUserStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldSearchUserStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("Personal Details");

        jLabelFNameUserStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelFNameUserStaff.setText("First name");

        jTextFieldFormNoUserStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabelDesignationUserStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelDesignationUserStaff.setText("Designation");

        jTextFieldDesignationUserStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Identity Number");

        jTextFieldIDUserStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jTextFieldFNameUserStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabelFormNoUserStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelFormNoUserStaff.setText("W&OP Number");

        jLabelMNameUserStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelMNameUserStaff.setText("Middle Name");

        jTextFieldMNameUsrStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabelLNameUserStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelLNameUserStaff.setText("Last Name");

        jTextFieldLNameUserStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabelGenderUserStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelGenderUserStaff.setText("Gender");

        jTextFieldGenderUserStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldGenderUserStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGenderUserStaffActionPerformed(evt);
            }
        });

        jLabelContactUserStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelContactUserStaff.setText("Contact no");

        jTextFieldContactUserStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabelBDayUserStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelBDayUserStaff.setText("Date Of Birth");

        jTextFieldBDayUserStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldBDayUserStaff.setText("Year/month/day");

        jLabelGrdeUserStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelGrdeUserStaff.setText("Grade");

        jTextFieldCivilStatusUserStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabelAppointmentUserStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelAppointmentUserStaff.setText("First Appointment Date");

        jTextFieldAppointmentUserStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabelAddressUserStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelAddressUserStaff.setText("Address");

        jLabelCivilStatusUserStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCivilStatusUserStaff.setText("Civil Status");

        jTextFieldAddressStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jTextFieldGradeUserStaff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lbl_img1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_img1.setForeground(new java.awt.Color(0, 51, 153));
        lbl_img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentinformationsystem/Person.png"))); // NOI18N
        lbl_img1.setText("Display Image");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabelFormNoUserStaff)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldFormNoUserStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabelContactUserStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldContactUserStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelGrdeUserStaff, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelGenderUserStaff, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelFNameUserStaff, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldGradeUserStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldGenderUserStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldCivilStatusUserStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldFNameUserStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabelCivilStatusUserStaff))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelAppointmentUserStaff)
                                    .addComponent(jLabelAddressUserStaff))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldAddressStaff)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jTextFieldAppointmentUserStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 250, Short.MAX_VALUE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelMNameUserStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelBDayUserStaff))
                                        .addGap(28, 28, 28))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldMNameUsrStaff)
                                    .addComponent(jTextFieldIDUserStaff)
                                    .addComponent(jTextFieldBDayUserStaff))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabelDesignationUserStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldDesignationUserStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabelLNameUserStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldLNameUserStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(3, 3, 3)))
                        .addGap(22, 22, 22)
                        .addComponent(lbl_img1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFormNoUserStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFormNoUserStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldIDUserStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFNameUserStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFNameUserStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMNameUserStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMNameUsrStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelLNameUserStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldLNameUserStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldGenderUserStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelGenderUserStaff)
                            .addComponent(jLabelBDayUserStaff)
                            .addComponent(jTextFieldBDayUserStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDesignationUserStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDesignationUserStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldGradeUserStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelGrdeUserStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAppointmentUserStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAppointmentUserStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lbl_img1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCivilStatusUserStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCivilStatusUserStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAddressUserStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAddressStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContactUserStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldContactUserStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(182, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSearchUserStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchUserStaffActionPerformed

    }//GEN-LAST:event_jTextFieldSearchUserStaffActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextFieldSearchUserStaff.setText("");
        jTextFieldFormNoUserStaff.setText("");
        jTextFieldDesignationUserStaff.setText("");
        jTextFieldIDUserStaff.setText("");
        jTextFieldFNameUserStaff.setText("");
        jTextFieldMNameUsrStaff.setText("");
        jTextFieldLNameUserStaff.setText("");
        jTextFieldGenderUserStaff.setText("");
        jTextFieldContactUserStaff.setText("");
        jTextFieldBDayUserStaff.setText("");
        jTextFieldCivilStatusUserStaff.setText("");
        jTextFieldAppointmentUserStaff.setText("");
        jTextFieldAddressStaff.setText("");
        jTextFieldGradeUserStaff.setText("");
    
        lbl_img1.setIcon(null);
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldGenderUserStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGenderUserStaffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGenderUserStaffActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new UserIndividualSpouse().setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new StaffDetails().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldSearchUserStaffKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchUserStaffKeyReleased
        ResultSet rs = null;
        PreparedStatement pst = null;

        try (Connection conn = dbconnect.java_db()) {
            String sql = "select * from staff where identity_number=? ";

            pst = conn.prepareStatement(sql);
            pst.setString(1, jTextFieldSearchUserStaff.getText());
            rs = pst.executeQuery();
            while (rs.next()) {

                String add1 = rs.getString("form_id");
                jTextFieldFormNoUserStaff.setText(add1);
                String add2 = rs.getString("designation");
                jTextFieldDesignationUserStaff.setText(add2);
                String add3 = rs.getString("identity_number");
                jTextFieldIDUserStaff.setText(add3);
                String add4 = rs.getString("first_name");
                jTextFieldFNameUserStaff.setText(add4);
                String add5 = rs.getString("middle_name");
                jTextFieldMNameUsrStaff.setText(add5);
                String add6 = rs.getString("last_name");
                jTextFieldLNameUserStaff.setText(add6);
                String add7 = rs.getString("gender");
                jTextFieldGenderUserStaff.setText(add7);
                String add8 = rs.getString("contact");
                jTextFieldContactUserStaff.setText(add8);
                String add9 = rs.getString("dob");
                jTextFieldBDayUserStaff.setText(add9);
                String add10 = rs.getString("grade");
                jTextFieldGradeUserStaff.setText(add10);
                String add11 = rs.getString("first_appointment_date");
                jTextFieldAppointmentUserStaff.setText(add11);
                String add12 = rs.getString("civil_status");
                jTextFieldCivilStatusUserStaff.setText(add12);
                String add13 = rs.getString("address");
                jTextFieldAddressStaff.setText(add13);
                byte[] img = rs.getBytes("image");
                ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(lbl_img1.getWidth(), lbl_img1.getHeight(), Image.SCALE_SMOOTH));
                lbl_img1.setIcon(imageIcon);
            }
        } catch (Exception e) {

        } finally {

            try {

                rs.close();
                pst.close();

            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_jTextFieldSearchUserStaffKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                
//
//
//
//}
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(UserIndividual.class  
//
//.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } 
//
//}

//catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(UserIndividual.class  
//
//.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } 
//
//
//
//catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(UserIndividual.class  
//
//.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } 
//
//
//
//catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(UserIndividual.class  
//
//.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserIndividualStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelAddressUserStaff;
    private javax.swing.JLabel jLabelAppointmentUserStaff;
    private javax.swing.JLabel jLabelBDayUserStaff;
    private javax.swing.JLabel jLabelCivilStatusUserStaff;
    private javax.swing.JLabel jLabelContactUserStaff;
    private javax.swing.JLabel jLabelDesignationUserStaff;
    private javax.swing.JLabel jLabelFNameUserStaff;
    private javax.swing.JLabel jLabelFormNoUserStaff;
    private javax.swing.JLabel jLabelGenderUserStaff;
    private javax.swing.JLabel jLabelGrdeUserStaff;
    private javax.swing.JLabel jLabelLNameUserStaff;
    private javax.swing.JLabel jLabelMNameUserStaff;
    private javax.swing.JLabel jLabelSearchUserStaff;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextFieldAddressStaff;
    private javax.swing.JTextField jTextFieldAppointmentUserStaff;
    private javax.swing.JTextField jTextFieldBDayUserStaff;
    private javax.swing.JTextField jTextFieldCivilStatusUserStaff;
    private javax.swing.JTextField jTextFieldContactUserStaff;
    private javax.swing.JTextField jTextFieldDesignationUserStaff;
    private javax.swing.JTextField jTextFieldFNameUserStaff;
    private javax.swing.JTextField jTextFieldFormNoUserStaff;
    private javax.swing.JTextField jTextFieldGenderUserStaff;
    private javax.swing.JTextField jTextFieldGradeUserStaff;
    private javax.swing.JTextField jTextFieldIDUserStaff;
    private javax.swing.JTextField jTextFieldLNameUserStaff;
    private javax.swing.JTextField jTextFieldMNameUsrStaff;
    private javax.swing.JTextField jTextFieldSearchUserStaff;
    private javax.swing.JLabel lbl_img1;
    // End of variables declaration//GEN-END:variables
}
